# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

before_install:
  - npm install -g gulp    # instalamos herramienta de construcción

script:
  - gulp install          # instalamos dependencias
  - gulp start &          # para desplegar microservicio
  - gulp stop             # para detener microservicio