# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

build:
  pre_ci:
    - npm install -g gulp-cli
  ci:
    - gulp install
    - gulp test            # ejecución de tests unitarios
    - gulp start           # para desplegar microservicio
    - gulp stop           # para detener microservicio
