# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

build:
  ci: # Construcción para CI
    - npm install         # para instalar dependencias
    - npm start           # para desplegar microservicio
    - npm stop           # para detener microservicio
    - npm run test        # para ejecutar los test unitarios
