# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

# Construcción para CI
install:
  - npm install         # instalamos dependencias

scripts:
  - npm test            # ejecución de tests unitarios
  - npm start           # para desplegar microservicio
  - npm stop           # para detener microservicio
  - gulp test
  - gulp start
  - gulp stop
