# Lenguaje del proyecto en el que usamos integración continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

before_install:
  - npm install gulp

# Construcción para CI
install:
  - gulp install

script:
  - gulp test            # ejecución de tests unitarios
  - gulp start           # para desplegar microservicio
  - gulp stop           # para detener microservicio
