# Lenguaje del proyecto en el que usamos integraci贸n continua
language: node_js

# Versi贸n del lenguaje 
node_js:
  - 10.16.2

# Construcci贸n para CI
install:
  - npm install         # instalamos dependencias

scripts:
  - npm test            # ejecuci贸n de tests unitarios
