# Lenguaje del proyecto en el que usamos integraci贸n continua
language: node_js

# Versiones del lenguaje 
node_js:
  - 10.16.2
  - 12.10.0

before_install:
  - npm install gulp

# Construcci贸n para CI
install:
#  - npm install         # instalamos dependencias
  - gulp install

scripts:
#  - npm test            # ejecuci贸n de tests unitarios
#  - npm start           # para desplegar microservicio
#  - npm stop           # para detener microservicio
  - gulp test            # ejecuci贸n de tests unitarios
  - gulp start           # para desplegar microservicio
  - gulp stop           # para detener microservicio
